# configurations for sharing folders between docker containers and host machine
#
### format ###
#
# machien_name:
#    /host/machine/from/folder1: /docker/container/to/folder1
#    /host/machine/from/folder2: /docker/container/to/folder2
#
# e.g.
#ros-indigo-base:
#    /home/user/ros/indigo: /home/vagrant/ros/indigo
