# configurations for sharing folders between docker containers and host machine
#
### format ###
#
# machien_name:
#    /host/machine/from/folder1: /docker/container/to/folder1
#    /host/machine/from/folder2: /docker/container/to/folder2
#
# e.g.
#ros-indigo-base:
#    /home/hkhambha/ros/indigo: /home/vagrant/ros/indigo
#ros-hydro-base:
#    /home/hkhambha/ros/hydro: /home/vagrant/ros/hydro
ros-indigo-devel:
    /home/hkhambha/ros/indigo: /home/vagrant/ros/indigo
ros-indigo-spencer:
    /home/hkhambha/ros/indigo: /home/vagrant/ros/indigo
